"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import styles from "./SponsorDashboard.module.css";

type Campaign={id:string;name:string;status:string;starts_at:string|null;ends_at:string|null};
type Metric={metric_date:string;ticket_uploads:number;valid_tickets:number;rejected_tickets:number;unique_participants:number;attributed_sales:number;rewards_won:number;rewards_redeemed:number;points_awarded:number};
type Budget={media_budget:number;rewards_budget:number;other_costs:number;estimated_margin_percentage:number};
const money=(value:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(value);

export default function SponsorDashboard(){
 const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [selected,setSelected]=useState("");const [metrics,setMetrics]=useState<Metric[]>([]);const [budget,setBudget]=useState<Budget|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{void loadCampaigns()},[]);
 useEffect(()=>{if(selected)void loadMetrics(selected)},[selected]);
 async function loadCampaigns(){const {data,error}=await supabase.from("campaign_sponsors").select("campaign_id,campaigns(id,name,status,starts_at,ends_at)");if(error){console.error(error);setLoading(false);return}const list=(data??[]).map((r:any)=>r.campaigns).filter(Boolean);setCampaigns(list);if(list[0])setSelected(list[0].id);else setLoading(false)}
 async function loadMetrics(id:string){setLoading(true);const [{data:m},{data:b}]=await Promise.all([supabase.from("campaign_metrics_daily").select("*").eq("campaign_id",id).order("metric_date"),supabase.from("campaign_budgets").select("*").eq("campaign_id",id).maybeSingle()]);setMetrics((m??[]) as Metric[]);setBudget(b as Budget|null);setLoading(false)}
 const summary=useMemo(()=>{const sales=metrics.reduce((a,m)=>a+Number(m.attributed_sales),0);const valid=metrics.reduce((a,m)=>a+m.valid_tickets,0);const uploads=metrics.reduce((a,m)=>a+m.ticket_uploads,0);const participants=metrics.reduce((a,m)=>a+m.unique_participants,0);const rewards=metrics.reduce((a,m)=>a+m.rewards_won,0);const cost=(budget?.media_budget??0)+(budget?.rewards_budget??0)+(budget?.other_costs??0);const ticketAvg=valid?sales/valid:0;const roas=cost?sales/cost:0;const margin=(budget?.estimated_margin_percentage??0)/100;const roi=cost?((sales*margin-cost)/cost)*100:0;return{sales,valid,uploads,participants,rewards,cost,ticketAvg,roas,roi}},[metrics,budget]);
 const maxSales=Math.max(1,...metrics.map(m=>Number(m.attributed_sales)));const width=760,height=270,pad=42;const points=metrics.map((m,i)=>{const x=pad+(i/Math.max(1,metrics.length-1))*(width-pad*2);const y=height-pad-(Number(m.attributed_sales)/maxSales)*(height-pad*2);return{x,y,m}});const path=points.map((p,i)=>`${i?"L":"M"}${p.x},${p.y}`).join(" ");
 const funnel=[{label:"Tickets cargados",value:summary.uploads},{label:"Tickets válidos",value:summary.valid},{label:"Participantes",value:summary.participants},{label:"Premios ganados",value:summary.rewards}];const funnelMax=Math.max(1,...funnel.map(f=>f.value));
 return <div className={styles.page}>
  <div className={styles.heading}><div><h1>Resultados de campañas</h1><p>Ventas atribuidas, participación y retorno estimado de tu inversión.</p></div><select className={styles.select} value={selected} onChange={e=>setSelected(e.target.value)}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
  {!campaigns.length&&!loading?<div className={styles.panel}><div className={styles.empty}>Aún no tienes campañas vinculadas.<div className={styles.actions} style={{justifyContent:"center",marginTop:16}}><Link className={styles.button} href="/patrocinador/campanas/nueva">Crear primera campaña</Link></div></div></div>:<>
  <section className={styles.metrics}><div className={styles.metric}><span>Ventas atribuidas</span><strong>{money(summary.sales)}</strong><small>Tickets aprobados</small></div><div className={styles.metric}><span>ROAS atribuido</span><strong>{summary.roas.toFixed(2)}x</strong><small>Ventas ÷ inversión</small></div><div className={styles.metric}><span>Ticket promedio</span><strong>{money(summary.ticketAvg)}</strong><small>{summary.valid} tickets válidos</small></div><div className={styles.metric}><span>ROI estimado</span><strong>{summary.roi.toFixed(1)}%</strong><small>Con margen estimado</small></div></section>
  <section className={styles.charts}><article className={styles.panel}><h2>Ventas atribuidas en el tiempo</h2><p>Monto diario validado a partir de tickets de compra.</p><svg className={styles.chart} viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Gráfica de ventas atribuidas por día"><defs><linearGradient id="salesArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e3b956" stopOpacity=".35"/><stop offset="1" stopColor="#e3b956" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i=><line key={i} className={styles.gridLine} x1={pad} x2={width-pad} y1={pad+i*(height-pad*2)/4} y2={pad+i*(height-pad*2)/4}/>)}{points.length>1?<><path className={styles.area} d={`${path} L${points.at(-1)!.x},${height-pad} L${points[0].x},${height-pad} Z`}/><path className={styles.line} d={path}/>{points.map((p,i)=><circle key={i} className={styles.dot} cx={p.x} cy={p.y} r="4"><title>{p.m.metric_date}: {money(Number(p.m.attributed_sales))}</title></circle>)}</>:null}{points.filter((_,i)=>i%Math.max(1,Math.ceil(points.length/6))===0).map((p,i)=><text key={i} className={styles.axis} x={p.x} y={height-13} textAnchor="middle">{new Date(p.m.metric_date+"T12:00:00").toLocaleDateString("es-MX",{day:"2-digit",month:"short"})}</text>)}</svg></article>
  <article className={styles.panel}><h2>Embudo de participación</h2><p>De la carga del ticket hasta la entrega de premios.</p><div className={styles.bars}>{funnel.map(f=><div className={styles.barRow} key={f.label}><span>{f.label}</span><div className={styles.track}><div className={styles.fill} style={{width:`${Math.max(4,f.value/funnelMax*100)}%`}}/></div><strong>{f.value}</strong></div>)}</div></article></section>
  <article className={styles.panel}><h2>Detalle diario</h2><p>Información lista para exportar o conectar a un reporte ejecutivo.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Fecha</th><th>Ventas</th><th>Tickets válidos</th><th>Rechazados</th><th>Participantes</th><th>Premios</th></tr></thead><tbody>{[...metrics].reverse().map(m=><tr key={m.metric_date}><td>{new Date(m.metric_date+"T12:00:00").toLocaleDateString("es-MX")}</td><td>{money(Number(m.attributed_sales))}</td><td>{m.valid_tickets}</td><td>{m.rejected_tickets}</td><td>{m.unique_participants}</td><td>{m.rewards_won}</td></tr>)}</tbody></table></div></article></>}
 </div>
}
