"use client";
import { FormEvent, useEffect, useState } from "react";
import { Building2, Mail, Plus, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import styles from "./Patrocinadores.module.css";
type SponsorRow={id:string;name:string;plan_code:string;membership_status:string;membership_ends_at:string|null};
export default function SponsorsPage(){
 const [items,setItems]=useState<SponsorRow[]>([]); const [notice,setNotice]=useState(""); const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({organizationName:"",name:"",email:"",planCode:"premium"});
 async function load(){const {data,error}=await supabase.from("sponsor_organizations").select("id,name,plan_code,membership_status,membership_ends_at").order("created_at",{ascending:false}); if(error)setNotice(error.message); else setItems((data??[]) as SponsorRow[])}
 useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setNotice("");const {data:{session}}=await supabase.auth.getSession();const response=await fetch("/api/admin/sponsors",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify(form)});const result=await response.json();setNotice(result.message??result.error??"Resultado desconocido");if(response.ok){setForm({organizationName:"",name:"",email:"",planCode:"premium"});await load()}setLoading(false)}
 async function updatePlan(id:string,plan_code:string){const {error}=await supabase.from("sponsor_organizations").update({plan_code}).eq("id",id);setNotice(error?.message??"Plan actualizado.");await load()}
 return <div className={styles.page}><header><div><span>ADMINISTRACIÓN</span><h1>Patrocinadores</h1><p>Crea marcas, invita a su usuario responsable y administra su plan.</p></div><button onClick={()=>void load()}><RefreshCw/>Actualizar</button></header><div className={styles.grid}><form onSubmit={submit} className={styles.card}><h2><Plus/>Nuevo patrocinador</h2><label>Marca<input value={form.organizationName} onChange={e=>setForm({...form,organizationName:e.target.value})} required/></label><label>Nombre del responsable<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Correo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Plan<select value={form.planCode} onChange={e=>setForm({...form,planCode:e.target.value})}><option value="basic">Básico · Ticket</option><option value="intermediate">Intermedio · Ticket + QR</option><option value="premium">Premium · Ticket + QR + Mapa</option></select></label><button disabled={loading}>{loading?"Creando…":"Crear y enviar invitación"}</button>{notice&&<p>{notice}</p>}</form><section className={styles.card}><h2><Building2/>Marcas registradas</h2><div className={styles.list}>{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.membership_status}</small></div><select value={item.plan_code??"basic"} onChange={e=>void updatePlan(item.id,e.target.value)}><option value="basic">Básico</option><option value="intermediate">Intermedio</option><option value="premium">Premium</option></select></article>)}{!items.length&&<p>No hay patrocinadores todavía.</p>}</div></section></div></div>
}
