"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MapPin, Phone, Save, ShieldCheck } from "lucide-react";
import { getCurrentRole, supabase } from "@/lib/supabase";
import { getStateCode, LMB_TEAMS, MEXICO_STATES } from "@/lib/mexicoCatalog";
import styles from "./CompletarRegistro.module.css";
const VERSION="1.0";
export default function CompletarRegistro(){
 const router=useRouter(); const [phone,setPhone]=useState("");const [state,setState]=useState("");const [municipality,setMunicipality]=useState("");const [favoriteTeam,setFavoriteTeam]=useState("");const [municipalities,setMunicipalities]=useState<string[]>([]);const [acceptPrivacy,setAcceptPrivacy]=useState(false);const [acceptTerms,setAcceptTerms]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const code=getStateCode(state);if(!code){setMunicipalities([]);return;}fetch(`/api/geo/municipalities?state=${code}`).then(r=>r.json()).then((p:{municipalities?:string[]})=>setMunicipalities(p.municipalities??[])).catch(()=>setError("No fue posible cargar los municipios."));},[state]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!acceptPrivacy||!acceptTerms){setError("Debes aceptar los documentos legales para continuar.");return;}setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return;}const acceptedAt=new Date().toISOString();const {error:updateError}=await supabase.from("profiles").update({phone:phone.trim(),state,municipality,favorite_team:favoriteTeam,registration_completed:true,updated_at:acceptedAt}).eq("id",user.id);if(updateError){setError(updateError.message);setLoading(false);return;}const {error:consentError}=await supabase.from("user_consents").upsert([{user_id:user.id,document_type:"privacy",document_version:VERSION,accepted_at:acceptedAt},{user_id:user.id,document_type:"terms",document_version:VERSION,accepted_at:acceptedAt}],{onConflict:"user_id,document_type,document_version"});if(consentError){setError(consentError.message);setLoading(false);return;}await supabase.auth.updateUser({data:{registration_completed:true,phone,state,municipality,favorite_team:favoriteTeam,privacy_accepted_version:VERSION,terms_accepted_version:VERSION}});const role=await getCurrentRole();router.replace(role==="admin"?"/admin":role==="sponsor"?"/patrocinador":"/usuario");}
 return <main className={styles.page}><section className={styles.card}><img src="/images/logo-home-run.png" alt="Home Run Rewards"/><span>Último paso</span><h1>Completa tu cuenta</h1><p>Google nos compartió tu nombre y correo. Agrega los datos necesarios para personalizar tus campañas y recompensas.</p><form onSubmit={submit}>
 <label>Teléfono<div><Phone/><input type="tel" minLength={10} value={phone} onChange={e=>setPhone(e.target.value)} required/></div></label>
 <label>Estado<div><MapPin/><select value={state} onChange={e=>{setState(e.target.value);setMunicipality("")}} required><option value="">Selecciona un estado</option>{MEXICO_STATES.map(s=><option key={s.code} value={s.name}>{s.name}</option>)}</select></div></label>
 <label>Municipio<div><MapPin/><select value={municipality} onChange={e=>setMunicipality(e.target.value)} disabled={!state} required><option value="">Selecciona un municipio</option>{municipalities.map(m=><option key={m}>{m}</option>)}</select></div></label>
 <label>Equipo favorito<div><ShieldCheck/><select value={favoriteTeam} onChange={e=>setFavoriteTeam(e.target.value)} required><option value="">Selecciona tu equipo</option>{LMB_TEAMS.map(t=><option key={t}>{t}</option>)}</select></div></label>
 <fieldset><label><input type="checkbox" checked={acceptPrivacy} onChange={e=>setAcceptPrivacy(e.target.checked)}/> Acepto el <Link href="/aviso-de-privacidad" target="_blank">Aviso de Privacidad</Link>.</label><label><input type="checkbox" checked={acceptTerms} onChange={e=>setAcceptTerms(e.target.checked)}/> Acepto los <Link href="/terminos-y-condiciones" target="_blank">Términos y Condiciones</Link>.</label></fieldset>{error&&<p className={styles.error}>{error}</p>}<button disabled={loading}><Save/>{loading?"Guardando...":"Completar registro"}</button></form></section></main>;
}
