import Link from "next/link";
import { BadgeCheck, Camera, Gift, MapPinned, QrCode, ReceiptText, Sparkles, Store, Trophy } from "lucide-react";
import CampaignBaseballScene from "@/components/CampaignBaseballScene";
import styles from "@/app/campanas/Campanas.module.css";

const campanas = [
 {numero:"Dinámica 01",titulo:"Búsqueda QR",descripcion:"Encuentra códigos ocultos, escanéalos desde tu celular y descubre al instante si ganaste una recompensa.",Icono:QrCode,IconoSecundario:Camera,beneficios:["Escaneo directo desde la cámara","Premios y puntos al instante","Sin encuesta durante la búsqueda"],acento:"qr"},
 {numero:"Dinámica 02",titulo:"Recompensa en mapa",descripcion:"Elige un premio cercano, sigue la ruta hasta la ubicación y completa la trivia para desbloquearlo.",Icono:MapPinned,IconoSecundario:Trophy,beneficios:["Ubicaciones y premios disponibles","Progreso de distancia en tiempo real","Trivia y experiencia de recompensa"],acento:"map"},
 {numero:"Dinámica 03",titulo:"Visita a marca",descripcion:"Compra con una marca participante, carga tu ticket y valida la visita para obtener puntos o beneficios.",Icono:Store,IconoSecundario:ReceiptText,beneficios:["Carga y lectura de ticket","Validación de ubicación","Premios de marcas aliadas"],acento:"brand"},
];
export default function CampaignSection(){return <section id="campanas" className={styles.page} aria-labelledby="titulo-campanas"><div className={styles.heroSection}><span className={styles.eyebrow}><Sparkles/>Dinámicas interactivas</span><h2 id="titulo-campanas">Tres formas de jugar,<span>una sola experiencia.</span></h2><p className={styles.introduction}>Participa en campañas QR, busca premios en el mapa o visita marcas aliadas. Arrastra la pelota, gira la vista y usa el gesto de pinza para acercarla.</p><CampaignBaseballScene/></div><div className={styles.campaignSection}><div className={styles.sectionHeading}><span><Sparkles/>Cómo puedes participar</span><h2>Elige tu dinámica</h2><p>Las campañas activas se publican dentro de tu cuenta y conservan el mismo flujo en celular, tablet y computadora.</p></div><div className={styles.campaignGrid}>{campanas.map(({numero,titulo,descripcion,Icono,IconoSecundario,beneficios,acento})=><article key={titulo} className={`${styles.campaignCard} ${styles[acento]}`}><div className={styles.cardTop}><div className={styles.mainIcon}><Icono/></div><div className={styles.secondaryIcon}><IconoSecundario/></div></div><span className={styles.campaignNumber}>{numero}</span><h3>{titulo}</h3><p className={styles.cardDescription}>{descripcion}</p><div className={styles.divider}/><ul>{beneficios.map((beneficio)=><li key={beneficio}><BadgeCheck/>{beneficio}</li>)}</ul><Link href="/login" className={styles.primaryButton}><Gift/>Entrar para participar</Link></article>)}</div></div></section>}
