"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import styles from "../../SponsorDashboard.module.css";

export default function NewCampaign(){const router=useRouter();const [orgId,setOrgId]=useState("");const [name,setName]=useState("");const [brand,setBrand]=useState("");const [description,setDescription]=useState("");const [minimum,setMinimum]=useState("300");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [media,setMedia]=useState("0");const [rewards,setRewards]=useState("0");const [margin,setMargin]=useState("30");const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{void (async()=>{const {data}=await supabase.from("sponsor_members").select("organization_id").limit(1).maybeSingle();setOrgId(data?.organization_id??"")})()},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const {data:{user}}=await supabase.auth.getUser();if(!user||!orgId)throw new Error("No se encontró la organización del patrocinador.");const startsAt=new Date(`${start}T00:00:00`).toISOString();const endsAt=new Date(`${end}T23:59:59`).toISOString();const {data:campaign,error}=await supabase.from("campaigns").insert({type:"brand",name,sponsor:brand,description,status:"draft",starts_at:startsAt,ends_at:endsAt,participation_limit:5,points_on_success:100,created_by:user.id,metadata:{createdBySponsor:true}}).select("id").single();if(error)throw error;const [{error:linkError},{error:ruleError},{error:budgetError}]=await Promise.all([supabase.from("campaign_sponsors").insert({campaign_id:campaign.id,organization_id:orgId,approval_status:"in_review"}),supabase.from("brand_rules").insert({campaign_id:campaign.id,expected_brand:brand,minimum_total:Number(minimum),required_products:[],confidence_threshold:.8,automatic_approval:false}),supabase.from("campaign_budgets").insert({campaign_id:campaign.id,media_budget:Number(media),rewards_budget:Number(rewards),estimated_margin_percentage:Number(margin)})]);if(linkError||ruleError||budgetError)throw linkError||ruleError||budgetError;router.push("/patrocinador/campanas")}catch(err){setMessage(err instanceof Error?err.message:"No fue posible crear la campaña.")}finally{setSaving(false)}}
 return <div className={styles.page}><div className={styles.heading}><div><h1>Nueva campaña de marca</h1><p>Se enviará a revisión administrativa antes de publicarse.</p></div></div><form className={styles.panel} onSubmit={submit} style={{display:"grid",gap:16,maxWidth:820}}><label>Nombre de la campaña<input required value={name} onChange={e=>setName(e.target.value)} style={input}/></label><label>Marca o comercio<input required value={brand} onChange={e=>setBrand(e.target.value)} style={input}/></label><label>Descripción<textarea required value={description} onChange={e=>setDescription(e.target.value)} rows={4} style={input}/></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14}}><label>Compra mínima<input required type="number" min="0" value={minimum} onChange={e=>setMinimum(e.target.value)} style={input}/></label><label>Fecha inicial<input required type="date" value={start} onChange={e=>setStart(e.target.value)} style={input}/></label><label>Fecha final<input required type="date" value={end} onChange={e=>setEnd(e.target.value)} style={input}/></label></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14}}><label>Inversión en medios<input type="number" min="0" value={media} onChange={e=>setMedia(e.target.value)} style={input}/></label><label>Presupuesto de premios<input type="number" min="0" value={rewards} onChange={e=>setRewards(e.target.value)} style={input}/></label><label>Margen estimado %<input type="number" min="0" max="100" value={margin} onChange={e=>setMargin(e.target.value)} style={input}/></label></div>{message?<p style={{color:"#ff9b9b"}}>{message}</p>:null}<button className={styles.button} type="submit" disabled={saving} style={{border:0,justifySelf:"start",cursor:"pointer"}}>{saving?"Guardando...":"Enviar a revisión"}</button></form></div>}
const input={display:"block",width:"100%",marginTop:7,boxSizing:"border-box" as const,border:"1px solid #30343c",borderRadius:12,padding:"12px 13px",background:"#0b0d10",color:"white",font:"inherit"};
